Will now try and connect to the db frist for upto 10 seconds
This handles the case where the postgres container is still starting up
when the migrations run.

diff --git a/migrate b/migrate
--- a/migrate
+++ b/migrate
@@ -1,6 +1,34 @@
 #!/bin/bash
 set -e
 
+function check_connection() {
+  set +e
+
+  iteration=$1
+
+  if (( $iteration > 5 ))
+  then
+    echo "Connection failed."
+    exit 1;
+  fi
+
+  echo "Testing connection attempt $iteration"
+
+  nc -z $DB_PORT_5432_TCP_ADDR $DB_PORT_5432_TCP_PORT
+
+  if [[ "$?" -ne "0" ]]
+  then
+    sleep 1
+    check_connection $((iteration + 1))
+  else
+    echo "Port is open!"
+  fi
+
+  set -e
+}
+
+check_connection 0
+
 /usr/local/pg-db-migrate/write_config "$@" > /tmp/database.json
 cd /usr/local/pg-db-migrate
 mkdir -p migrations
